apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w9g6a7xqh-nodejs
  janus-idp.io/tekton: w9g6a7xqh-nodejs
  backstage.io/kubernetes-id: w9g6a7xqh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w9g6a7xqh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
