apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w9g6a7xqh-nodejs 
  janus-idp.io/tekton: w9g6a7xqh-nodejs
  backstage.io/kubernetes-id: w9g6a7xqh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w9g6a7xqh-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml